// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apiserver

import (
	"github.com/moweilong/mo/pkg/server"
)

// Injectors from wire.go:

func InitializeWebServer(config *Config) (server.Server, error) {
	serverConfig := &ServerConfig{
		cfg: config,
	}
	serverServer, err := NewAggregatorServer(serverConfig)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
