name: Manage Tags and Changelog

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch: # 允许手动触发

env:
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.MO_TOKEN }}

jobs:
  Manage-Releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "kalandramo@gmail.com"
          git config --global user.name "moweilong"

      - name: Create Submodule Tags
        run: |
          main_tag=${GITHUB_REF#refs/tags/}
          directories=("entx" "cmd")
          
          for dir in "${directories[@]}"; do
            find "$dir" -name "go.mod" | sort -u | while read -r file; do
              submodule_path=$(dirname "$file")
              submodule_tag="${submodule_path}/${main_tag}"
              
              if ! git rev-parse "$submodule_tag" >/dev/null 2>&1; then
                git tag "$submodule_tag"
                git push origin "$submodule_tag"
              fi
            done
          done

      - name: Generate Release Notes
        id: release_notes
        run: |
          # 提取两个标签之间的提交记录
          # 处理首次发布没有上一个标签的情况
          if [ $(git tag --list | wc -l) -lt 2 ]; then
            # 如果标签数量少于2个，显示所有提交
            echo "All changes in this release:" > release_notes.md
            git log --pretty=format:"- %s" >> release_notes.md
          else
            prev_tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
            echo "Changes since $prev_tag:" > release_notes.md
            git log --pretty=format:"- %s" $prev_tag..$main_tag >> release_notes.md
          fi
          
          # 使用不同的分隔符避免冲突          echo 'RELEASE_NOTES<<___EOF___' >> $GITHUB_ENV
          cat release_notes.md >> $GITHUB_ENV
          echo '___EOF___' >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          # 解码base64内容
          body: ${{ fromBase64(env.RELEASE_NOTES) }}
          files: |
            CHANGELOG.md
          tag_name: ${{ github.ref_name }}