name: Manage Tags and Changelog

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch: # 允许手动触发

env:
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.MO_TOKEN }}

jobs:
  Manage-Releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "kalandramo@gmail.com"
          git config --global user.name "moweilong"

      - name: Create Submodule Tags
        run: |
          main_tag=${GITHUB_REF#refs/tags/}
          directories=("entx")
          
          for dir in "${directories[@]}"; do
            find "$dir" -name "go.mod" | sort -u | while read -r file; do
              submodule_path=$(dirname "$file")
              submodule_tag="${submodule_path}/${main_tag}"
              
              if ! git rev-parse "$submodule_tag" >/dev/null 2>&1; then
                git tag "$submodule_tag"
                git push origin "$submodule_tag"
              fi
            done
          done

      - name: Generate Release Notes
        id: release_notes
        run: |
          # 提取两个标签之间的提交记录
          if [ $(git tag --list | wc -l) -lt 2 ]; then
            echo "All changes in this release:" > release_notes.md
            git log --pretty=format:"- %s" >> release_notes.md
          else
            prev_tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
            echo "Changes since $prev_tag:" > release_notes.md
            git log --pretty=format:"- %s" $prev_tag..$main_tag >> release_notes.md
          fi
          
          # 使用base64编码避免特殊字符问题
          echo "RELEASE_NOTES=$(base64 -w 0 release_notes.md)" >> $GITHUB_ENV

      - name: Commit CHANGELOG Updates
        run: |
          main_tag=${GITHUB_REF#refs/tags/}
          git add CHANGELOG.md
          # 检查是否有变更
          if git diff --staged --quiet; then
            echo "No changes to CHANGELOG.md"
          else
            git commit -m "docs: update CHANGELOG.md for $main_tag"
            git push origin ${{ github.ref_name }}
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          files: |
            CHANGELOG.md
          tag_name: ${{ github.ref_name }}